cursor #e4e2e0
cursor_text_color #c4c8c2

foreground            #e4e2e0
background            #131313
selection_foreground  #2d312d
selection_background  #c4c8c2
url_color             #bdcabe

color0   #131313
color1   #e88868
color2   #66ca65
color3   #fced71
color4   #b1bfb2
color5   #525d53
color6   #bdcabe
color7   #c7d4c8
color8   #79837a
color9   #ffb79f
color10  #9ef29d
color11  #fff5a5
color12  #d2ded2
color13  #f3fff4
color14  #f7fff8
color15  #f8fff9
