cursor #e0e2e8
cursor_text_color #bfc7d2

foreground            #e0e2e8
background            #101418
selection_foreground  #12334b
selection_background  #accae8
url_color             #94ccff

color0   #101418
color1   #ff729d
color2   #7fff90
color3   #fff772
color4   #78b8f2
color5   #1b4a76
color6   #94ccff
color7   #eff7ff
color8   #999fa5
color9   #ff9fbc
color10  #a5ffb1
color11  #fffaa5
color12  #a4d3ff
color13  #b4dbff
color14  #cee8ff
color15  #f8fbff
