cursor #e2e2e6
cursor_text_color #c3c6d0

foreground            #e2e2e6
background            #121316
selection_foreground  #243142
selection_background  #bac7dd
url_color             #a4c9fc

color0   #121316
color1   #ff729b
color2   #7efc8f
color3   #fff772
color4   #8bb5ef
color5   #294974
color6   #a4c9fc
color7   #eff6ff
color8   #979ca3
color9   #ff9fbb
color10  #a5ffb2
color11  #fffaa5
color12  #b3d3ff
color13  #c0daff
color14  #d6e7ff
color15  #f8fbff
